jwt:
  secret: admin
  username: admin
  password: admin
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000